# Generated by Django 5.2.7 on 2025-10-18 13:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_type', models.CharField(choices=[('IN', '出勤'), ('OUT', '退勤'), ('BREAK_START', '休憩開始'), ('BREAK_END', '休憩終了')], max_length=12)),
                ('punched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('work_date', models.DateField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
