# Generated by Django 5.2.7 on 2025-10-19 06:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rank', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='hr_core.department')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('employment_type', models.CharField(choices=[('REGULAR', '正社員'), ('CONTRACT', '契約社員'), ('PARTTIME', 'パート・アルバイト'), ('DISPATCH', '派遣'), ('INTERN', 'インターン')], default='REGULAR', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', '在籍'), ('LEAVE', '休職'), ('RETIRED', '退職')], default='ACTIVE', max_length=20)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('retire_date', models.DateField(blank=True, null=True)),
                ('base_hours_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('note', models.TextField(blank=True, default='')),
                ('is_manager', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr_core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr_core.position')),
            ],
            options={
                'ordering': ['employee_code'],
            },
        ),
    ]
