# Generated by Django 5.2.7 on 2025-10-19 14:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0002_alter_department_options_alter_employee_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('punch_type', models.CharField(choices=[('IN', '出勤'), ('OUT', '退勤'), ('BREAK_START', '休憩開始'), ('BREAK_END', '休憩終了')], max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_punches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['punched_at'],
                'indexes': [models.Index(fields=['user', 'punched_at'], name='hr_core_att_user_id_509fcc_idx')],
            },
        ),
    ]
