# Generated by Django 5.2.7 on 2025-10-19 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_core', '0005_fix_overtime_tz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='overtimerequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={},
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='note',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='retire_date',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='base_hours_per_day',
            field=models.FloatField(default=8.0),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_core.department'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employment_type',
            field=models.CharField(choices=[('REGULAR', '正社員'), ('CONTRACT', '契約社員'), ('PARTTIME', 'パート/アルバイト'), ('DISPATCH', '派遣'), ('INTERN', 'インターン')], default='REGULAR', max_length=16),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_core.position'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=32),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
